<?php

define(APP_PATH, dirname(__FILE__).'/../../../app');
require_once(APP_PATH.'/config/main.php');
require_once(APP_PATH.'/config/Config.php');
require_once(APP_PATH.'/core/MVC/Model.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-02 at 18:44:15.
 */
class ModelTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Model
     */
    protected $model;
    protected $class;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->model = new Model;
        $this->class = new ReflectionClass('Model');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

     //using reflection for test protected methods
    protected function getMethod($name) {
        $method = $this->class->getMethod($name);
        $method->setAccessible(true);
        return $method;
    }

    //using reflection for test protected properties
    protected function getProperty($name) {
        $property = $this->class->getProperty($name);
        $property->setAccessible(true);
        return $property->getValue($this->model);
    }

    public function testDb() {
        $this->assertClassHasAttribute('db', 'Model');
    }

    public function testConfig() {
        $this->assertClassHasAttribute('config', 'Model');
        $this->assertArrayHasKey('driver', $this->getProperty('config'));
        $this->assertArrayHasKey('host', $this->getProperty('config'));
        $this->assertArrayHasKey('dbname', $this->getProperty('config'));
        $this->assertArrayHasKey('username', $this->getProperty('config'));
        $this->assertArrayHasKey('password', $this->getProperty('config'));
    }
}
