<?php

define(APP_PATH, dirname(__FILE__).'/../../../app');
require_once(APP_PATH.'/config/main.php');
require_once(APP_PATH.'/config/Config.php');
require_once(APP_PATH.'/core/DB/DB.php');
require_once(APP_PATH.'/core/DB/MysqlDB.php');
require_once(APP_PATH.'/core/DB/DBFactory.php');
require_once(APP_PATH.'/core/DB/MysqlDBFactory.php');
require_once(APP_PATH.'/core/MVC/Model.php');
require_once(APP_PATH.'/core/MVC/MysqlModel.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-02 at 18:45:11.
 */
class MysqlModelTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MysqlModel
     */
    protected $model;
    protected $class;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->model = new MysqlModel;
        $this->class = new ReflectionClass('MysqlModel');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    //using reflection for test protected properties
    protected function getProperty($name) {
        $property = $this->class->getProperty($name);
        $property->setAccessible(true);
        return $property->getValue($this->model);
    }

    public function testDb() {
        $this->assertClassHasAttribute('db', 'MysqlModel');
        $this->assertInstanceOf('MysqlDB', $this->getProperty('db'));
    }
}
